### PR TITLE
SP-302 Fix checkout issue

### PR DESCRIPTION
**Pull request by virtua-wkogut**

### CODE REVIEW

**Comment by jorgb90** [comment]
@virtua-wkogut Thanks for the quick fix!

**Review by p-maguire — APPROVED** [review]

**Comment by jorgb90** [comment]
@virtua-wkogut Mm still getting: [2022-11-04T10:54:37.788505+00:00] main.CRITICAL: TypeError: Argument 2 passed to Bitpay\BPCheckout\Plugin\Onepage\SuccessPlugin::afterExecute() must be an instance of Magento\Framework\View\Result\Page, instance of Magento\Framework\Controller\Result\Redirect\Interceptor given, called in vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in vendor/bitpay/module-bpcheckout/Plugin/Onepage/SuccessPlugin.php:17

**Comment by virtua-wkogut** [comment]
@jorgb90 could you provide steps to recreate, because I don't have this error, thanks

**Comment by jorgb90** [comment]
@virtua-wkogut its just people doing a checkout on our production site. Is this a new error or should it be fixed with this pull request? (cause maybe I need to regenerate) Here is the full trace:

[2022-11-04T10:54:37.788505+00:00] main.CRITICAL: TypeError: Argument 2 passed to Bitpay\BPCheckout\Plugin\Onepage\SuccessPlugin::afterExecute() must be an instance of Magento\Framework\View\Result\Page, instance of Magento\Framework\Controller\Result\Redirect\Interceptor given, called in /public_html/vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in /public_html/vendor/bitpay/module-bpcheckout/Plugin/Onepage/SuccessPlugin.php:17
Stack trace:
#0 /public_html/vendor/magento/framework/Interception/Interceptor.php(146): Bitpay\BPCheckout\Plugin\Onepage\SuccessPlugin->afterExecute()
#1 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}()
#2 /public_html/generated/code/Magento/Checkout/Controller/Onepage/Success/Interceptor.php(23): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callPlugins()
#3 /public_html/vendor/magento/framework/App/Action/Action.php(111): Magento\Checkout\Controller\Onepage\Success\Interceptor->execute()
#4 /public_html/vendor/magento/module-checkout/Controller/Onepage.php(161): Magento\Framework\App\Action\Action->dispatch()
#5 /public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Controller\Onepage->dispatch()
#6 /public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callParent()
#7 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}()
#8 /public_html/generated/code/Magento/Checkout/Controller/Onepage/Success/Interceptor.php(32): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callPlugins()
#9 /public_html/vendor/magento/framework/App/FrontController.php(245): Magento\Checkout\Controller\Onepage\Success\Interceptor->dispatch()
#10 //public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#11 /public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#12 /public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#13 /public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#14 /public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#15 /public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#16 /public_html/vendor/mirasvit/module-push-notification/src/PushNotification/Plugin/Framework/App/FrontController/FirebaseServerWorkerJsResponsePlugin.php(74): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#17 /public_html/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\PushNotification\Plugin\Framework\App\FrontController\FirebaseServerWorkerJsResponsePlugin->aroundDispatch()
#18 /public_html/vendor/mirasvit/module-cache-warmer/src/CacheWarmer/Plugin/Debug/OnHitPlugin.php(145): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#19 /public_html/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\CacheWarmer\Plugin\Debug\OnHitPlugin->aroundAroundDispatch()
#20 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}()
#21 /public_html/generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php(23): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins()
#22 /public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch()
#23 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#24 /public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#25 /public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#26 /public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#27 /public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#28 /public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#29 {main} [] []

**Pull request merged**
